id: IEAC114EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:21:28+00:00'
last_modified: '2022-06-08T06:47:17.656444+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30396
  title: དམ་ཚིག་ཐམས་ཅད་ཉམས་ཆགས་སྐོང་བའི་ལུང་བཤགས་པ་ཐམས་ཅད་ཀྱི་རྒྱུད་དྲི་མ་མེད་པའི་རྒྱལ་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D53:
      image_group_id: I6102
      title: ''
      total_pages: 196
      order: 1
      base_file: 4D53.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
